---
# tasks file for ansible-dcos-common

# - name: Turn off firewalld for docker
#   service: name=firewalld state=stopped enabled=no

- name: Upgrade all packages
  yum: name=* state=latest

- name: Install packages for data compression utilities
  yum: name={{ item }} state=present
  with_items:
    - tar
    - xz
    - unzip
    - curl
    - ipset

- name: Set Selinux permissive
  selinux: policy=targeted state=permissive
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"

- name: Set Selinux permissive via cli
  command: setenforce 0
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"

- name: Add group nogroup
  group: name=nogroup state=present

- name: Enable OverlayFS
  lineinfile: dest=/etc/modules-load.d/overlay.conf regexp="^overlay" line=overlay state=present create=yes

- name: Load kernel module
  modprobe: name=overlay state=present

- name: Configure proxy for yum if needed
  lineinfile: dest=/etc/yum.conf regexp="^proxy" line="proxy={{ env.http_proxy }}" state="present" create=yes

- name: Configure yum to use the Docker yum repo
  template: src=docker.repo.j2 dest=/etc/yum.repos.d/docker.repo

- name: Ensure /etc/systemd/system/docker.service.d exists
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: Configure systemd to run the Docker Daemon with OverlayFS
  template: src=override.conf.j2 dest=/etc/systemd/system/docker.service.d/override.conf

- name: Configure docker proxy if needed
  template: src=http-proxy.conf.j2 dest=/etc/systemd/system/docker.service.d/http-proxy.conf

- name: Install the Docker engine
  yum: name=docker-engine state=latest

- name: stop docker
  systemd: state=stopped name=docker

# check if /var/lib/docker is a symlink
- stat: path=/var/lib/docker 
  register: var_lib_docker

- name: move /var/lib/docker to /pkg/docker
  command: "{{ item }}" 
  with_items: 
  - cp -ra /var/lib/docker /pkg
  - rm -rf /var/lib/docker
  - ln -s /pkg/docker /var/lib/docker
  when: var_lib_docker.stat.isdir is defined and var_lib_docker.stat.isdir

#  synchronize: mode=pull src=/var/lib/docker dest=/pkg/docker recursive=true
#  when: var_lib_docker.stat.isdir is defined and var_lib_docker.stat.isdir

#- name: remove the folder (only if it is a folder)
#  file: path=/var/lib/docker state=absent
#  when: sites_available.stat.isdir is defined and sites_available.stat.isdir

#- name: setup link /var/lib/docker -> /pkg/docker
#  file: path=/var/lib/docker 
#        src=/pkg/docker 
#        state=link 
#        force=yes

- systemd: state=restarted daemon_reload=yes name=docker

- name: Enable and start the Docker engine
  service: name=docker  enabled=yes state=started

